FROM alpine:latest

WORKDIR /opt/work/

RUN mkdir -p /etc/wgctl/server /etc/wgctl/client /etc/wgctl/wireguard
RUN apk update && apk upgrade && apk add --no-cache -u wireguard-tools curl

COPY work /opt/work/work

ENTRYPOINT ["/opt/work/work"]